create new prediction_types for mean and median #367
reichlab/docs.zoltardata pull request #15
Opened 2024-04-03 18:53 UTC by matthewcornell

closes [create new prediction_types for mean and median #367]. removes the beta feature to download the Zoltar database for local use

2024-04-03 19:26 UTC, nickreich commented on docs/FileFormats.md
>      - `"point`: A numeric point prediction with a single `value` key.
are we missing a close quote here?

2024-04-03 19:27 UTC, nickreich commented on docs/FileFormats.md
>      - `"point`: A numeric point prediction with a single `value` key.
it should be `"point"` not `"point`

2024-04-03 19:28 UTC, nickreich commented on docs/FileFormats.md
> +    - `"mean"`, `"median"`, and `"mode"`: Similar to `"point"` but with clear semantics.
I suggest making this line stand on its own, if nothing else to ready ourselves for a removal of the "point" row that might be removed at a later point. So maybe the text after the full colon could read:
"A numeric prediction with a single `value` key, indicating the summary statistic indicated by the name, e.g. the mean."

2024-04-03 19:30 UTC, nickreich commented on docs/ForecastQueryFormat.md
> +### Prediction type conversion
Could we add something in this section about how the conversion is requested? It's not clear to me what tool someone would use to activate the conversion of point types. Maybe this should be a separate issue.

2024-04-03 19:32 UTC, nickreich commented on docs/Validation.md
> +### `Point` Prediction Elements (also applies to `mean`, `median`, and `mode`)
Same as comment above to feature the new types more on equal footing with point, could we make this header

### `point`, `mean`, `median`, and `mode` Prediction Elements

2024-04-03 19:33 UTC, nickreich commented on docs/Validation.md
> +These tests are performed when a forecast is created or updated. For all target types, only [valid Prediction Types](Targets.md#valid-prediction-types-by-target) are accepted. Note: `point` also appl
I suggest making these changes explicitly in the text below, not just once at the top. Will save us work later and be cleaner now.

2024-04-03 19:37 UTC, nickreich requested changes
I have a few minor requested changes. My main overarching comment is that I think there are some places where we could save ourselves time later (when removing or deactivating the point prediction type) by just putting mean/median/mode on equal footing in the documentation now.

2024-04-04 16:37 UTC, matthewcornell commented
Thanks very much for the comments, @nickreich . I've incorporated them in the new commit.

2024-04-04 16:45 UTC, nickreich approved these changes
Thanks, @matthewcornell . LGTM!

2024-04-08 12:32 UTC, merged